"""V3 parity fixture expected values are hand-authored, not generated by fold."""
import datetime as dt
import json
from pathlib import Path

import pytest

from gateway.program_progress import fold_week_progress, next_workout, week_window

FIXTURE = json.loads((Path(__file__).parent / 'fixtures/week_progress_v3.json').read_text())


@pytest.mark.parametrize('case', FIXTURE['cases'], ids=lambda c:c['name'])
def test_progress_parity(case):
    assert fold_week_progress(case['plan'], case['weekNumber'], case['logs'], case['reps'], case['trainingSessions']) == case['expected']
    result = next_workout(case['plan'],case['logs'],case['now'])
    assert (result['workoutId'] if result else None) == case['expectedNextWorkoutId']


def test_dst_window_is_167_hours_and_next_resumes_frozen_snapshot():
    plan = FIXTURE['cases'][0]['plan']
    start,end=week_window(plan,1)
    assert (end.astimezone(dt.timezone.utc)-start.astimezone(dt.timezone.utc)).total_seconds()==167*3600
    snapshot={'workoutId':'w1s1','revision':1,'blocks':[{'drillId':'original'}]}
    logs=[{'id':'p1_w1s1','source':'plan','planId':'p1','workoutId':'w1s1','endedAt':None,'workoutSnapshot':snapshot}]
    assert next_workout(plan,logs,'2026-03-04T12:00:00Z')==snapshot


def test_legacy_fold_cannot_silently_switch_taxonomy():
    with pytest.raises(ValueError, match='schemaVersion 3'):
        fold_week_progress({'schemaVersion':2},1,[],[],[])
