import { useState } from "react";
import { InsightTabs, InsightsControls } from "./InsightsPage";
import ExpandedReport from "./ExpandedReport";
import { expandedRequest } from "./lib/expandedQuery";
import type { ExpandedRequest } from "./lib/expandedQuery";
import { previewInsights } from "./lib/preview";
import type { InsightAccess } from "./lib/expanded";

export default function InsightsPreview() {
  const [request, setRequest] = useState(() => expandedRequest(window.location.search));
  const [page, setPage] = useState(0), [state, setState] = useState("normal"), [role, setRole] = useState<InsightAccess>("admin");
  const data = previewInsights(request, page, state, role);
  const change = (patch: Partial<ExpandedRequest>) => { setRequest(value => ({ ...value, ...patch })); setPage(0); };
  return <div className="pt-pose portal-body pt-insights"><header className="portal-header"><span className="portal-brand"><span className="portal-brand-mark">P</span>POSETEK</span><span className="insights-note">Synthetic preview · no live data</span></header><main className="insights-shell"><div className="insights-filters"><label>Preview role<select value={role} onChange={event => { setRole(event.target.value as InsightAccess); change({ orgId: event.target.value === "admin" ? undefined : "northfield", teamId: undefined }); }}><option value="admin">Admin</option><option value="manager">Manager</option><option value="coach">Assigned coach</option></select></label><label>Preview state<select value={state} onChange={event => { setState(event.target.value); setPage(0); }}><option value="normal">Recorded data</option><option value="empty">Empty roster</option><option value="uncollected">Usage not collected</option><option value="loading">Loading</option><option value="error">Load failure</option></select></label></div><section className="insights-heading"><p className="eyebrow">Insights</p><h1>{data.scope.label}</h1><p>Understand your roster, successful testing, completed workouts and estimated active use.</p></section><InsightsControls choices={data.choices} request={request} scope={data.scope} loading={state === "loading"} onChange={change} onRefresh={() => setState("normal")} /><InsightTabs request={request} onChange={change} />{["overview", "testing"].includes(request.view) && <div className="insights-toolbar"><p className="insights-note">Testing coverage</p><div className="insights-toggle"><button aria-pressed={request.testingWindow === "cumulative"} onClick={() => change({ testingWindow: "cumulative" })}>Through selected end</button><button aria-pressed={request.testingWindow === "period"} onClick={() => change({ testingWindow: "period" })}>Selected period only</button></div></div>}{state === "loading" ? <p role="status">Loading complete Insights…</p> : state === "error" ? <div role="alert"><p>Insights could not be loaded. Retry or choose another scope.</p><button className="quiet-button" onClick={() => setState("normal")}>Retry Insights</button></div> : <div id="insights-report" role="tabpanel" aria-labelledby={`insights-tab-${request.view}`}><ExpandedReport data={data} request={request} onChange={change} page={page} onPrevious={() => setPage(value => value - 1)} onNext={() => setPage(value => value + 1)} playerLink={player => `#synthetic-${player.id}`} /></div>}</main></div>;
}
