import React,{CSSProperties,useEffect,useState} from 'react';
import {AbsoluteFill,Audio,Freeze,OffthreadVideo,Sequence,continueRender,delayRender,interpolate,Easing,staticFile,useCurrentFrame} from 'remotion';
import {PoseVisual} from './PoseVisual';
import {MovementPreview,ClubDashboard} from './RevisionScenes';
import map from './us-map.json';

const C={bg:'#04130e',panel:'#0a211a',lime:'#b7f34a',ink:'#f0f5ed',muted:'#a9bdb1',line:'#254036',mint:'#c1f5e5'};
const mono='"IBM Plex Mono",monospace',condensed='"Barlow Condensed",sans-serif';
const p=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.18,.78,.22,1)});
const title:CSSProperties={fontFamily:condensed,fontWeight:700,lineHeight:1.01,letterSpacing:'-.018em',textTransform:'uppercase',margin:0};
type Props={audioEnabled?:boolean;captions?:{start:number;end:number;text:string}[]};
function Fonts(){const [h]=useState(()=>delayRender('Investor brand fonts'));useEffect(()=>{Promise.all([['Barlow Condensed','barlow-700.woff2','700'],['Inter','inter-400.woff2','400'],['Inter','inter-600.woff2','600'],['IBM Plex Mono','plex-400.woff2','400']].map(async([name,file,weight])=>{const font=new FontFace(name,`url(${staticFile('fonts/'+file)})`,{weight});await font.load();(document.fonts as unknown as {add:(f:FontFace)=>void}).add(font);})).then(()=>continueRender(h));},[h]);return null;}
function Brand({large=false}:{large?:boolean}){return <div style={{display:'flex',alignItems:'center',gap:large?24:14,fontWeight:600,fontSize:large?54:28,letterSpacing:large?7:3}}><div style={{width:large?82:43,height:large?82:43,background:C.lime,color:C.bg,display:'grid',placeItems:'center',fontSize:large?60:32,borderRadius:3,position:'relative'}}>P<span style={{position:'absolute',right:-1,bottom:-1,width:large?17:10,height:large?17:10,background:C.bg}}/></div>POSETEK</div>;}
function Kicker({children}:{children:React.ReactNode}){return <div style={{fontFamily:mono,fontSize:23,letterSpacing:2.4,color:C.lime,textTransform:'uppercase'}}>{children}</div>;}
function Label({children,style={}}:{children:React.ReactNode;style?:CSSProperties}){return <div style={{fontFamily:mono,fontSize:20,color:C.muted,...style}}>{children}</div>;}
function Reveal({f,at=0,children,style={}}:{f:number;at?:number;children:React.ReactNode;style?:CSSProperties}){const q=p(f,at,at+16);return <div style={{opacity:q,transform:`translateY(${(1-q)*24}px)`,...style}}>{children}</div>;}
function Arrow({style={}}:{style?:CSSProperties}){return <span style={{fontSize:60,color:C.lime,...style}}>→</span>;}
function Scene({from,duration,children}:{from:number;duration:number;children:(f:number)=>React.ReactNode}){return <Sequence from={from} durationInFrames={duration}><SceneInner duration={duration}>{children}</SceneInner></Sequence>;}
function SceneInner({duration,children}:{duration:number;children:(f:number)=>React.ReactNode}){const f=useCurrentFrame();return <AbsoluteFill style={{opacity:p(f,0,10)*(duration===180?1:1-p(f,duration-8,duration)),background:C.bg}}>{children(f)}</AbsoluteFill>;}

function Opportunity({f}:{f:number}){return <>
 <div style={{position:'absolute',left:96,top:206,width:990,zIndex:2}}><Kicker>The opportunity</Kicker><Reveal f={f}><h1 style={{...title,fontSize:132,marginTop:34}}>Potential is<br/>everywhere.<br/><span style={{color:C.lime}}>Evidence isn’t.</span></h1></Reveal><Reveal f={f} at={58}><div style={{fontSize:33,color:C.muted,lineHeight:1.5,marginTop:37,maxWidth:760}}>A clearer path from today’s movement<br/>to tomorrow’s training.</div></Reveal></div>
 <div style={{position:'absolute',left:980,top:125,opacity:p(f,0,30)}}><PoseVisual frame={f} width={850} height={775}/></div>
 <div style={{position:'absolute',right:110,top:851}}><Label>Movement → insight → action</Label></div>
 </>;}

function Mission({f}:{f:number}){return <>
 <div style={{position:'absolute',left:96,top:166}}><Kicker>Our mission</Kicker><h2 style={{...title,fontSize:95,marginTop:22}}>Elite insight. <span style={{color:C.lime}}>Within reach.</span></h2></div>
 <Reveal f={f} at={0} style={{position:'absolute',left:116,top:343,width:335,height:467,border:`2px solid #45614f`,borderRadius:32,background:C.panel,overflow:'hidden'}}><Label style={{padding:'22px 25px',color:C.lime}}>01 / PHONE CAPTURE</Label><div style={{transform:'translateX(-56px) scale(.92)',transformOrigin:'top center'}}><MovementPreview index={5} f={f}/></div><div style={{position:'absolute',left:28,bottom:26,fontSize:26}}>Six standardized tests</div></Reveal>
 <Reveal f={f} at={25} style={{position:'absolute',left:510,top:550}}><Arrow/></Reveal>
 <Reveal f={f} at={28} style={{position:'absolute',left:600,top:336,width:560,height:500}}><Label style={{textAlign:'center',color:C.lime}}>02 / MOVEMENT ANALYSIS</Label><PoseVisual frame={f} width={560} height={453} compact/><Label style={{textAlign:'center'}}>Source-derived pose visualization</Label></Reveal>
 <Reveal f={f} at={64} style={{position:'absolute',left:1225,top:550}}><Arrow/></Reveal>
 <Reveal f={f} at={70} style={{position:'absolute',left:1325,top:360,width:480,borderTop:`2px solid ${C.line}`,paddingTop:30}}><Label style={{color:C.lime}}>03 / INDIVIDUAL INSIGHT</Label><h3 style={{...title,fontSize:81,marginTop:28}}>A focus for<br/>what comes<br/><span style={{color:C.lime}}>next.</span></h3><div style={{fontSize:27,color:C.muted,marginTop:27}}>Testing. Insight. Training.</div></Reveal>
 </>;}

const tests=['Sprint','Vertical jump','Broad jump','Dribbling','Change of direction','Shooting'];
function Assess({f}:{f:number}){return <><div style={{position:'absolute',left:96,top:163}}><Kicker>The product / Test</Kicker><h2 style={{...title,fontSize:94,marginTop:21}}>Six tests. <span style={{color:C.lime}}>One starting point.</span></h2></div><div style={{position:'absolute',left:96,right:96,top:312,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:22}}>{tests.map((name,i)=><div key={name} style={{height:268,position:'relative',background:C.panel,border:`1px solid ${C.line}`,borderRadius:14,overflow:'hidden'}}><div style={{position:'absolute',left:78,top:-3,transform:'scale(.78)',transformOrigin:'top left'}}><MovementPreview index={i} f={f}/></div><div style={{position:'absolute',left:25,bottom:21,fontSize:30,fontWeight:600}}><span style={{fontFamily:mono,fontSize:19,color:C.lime,marginRight:20}}>0{i+1}</span>{name}</div></div>)}</div></>;}

function Profile({f}:{f:number}){return <>
 <Label style={{position:'absolute',left:100,top:884,fontSize:22}}>Illustrative club and player data</Label>
 <div style={{position:'absolute',left:96,top:153}}><Kicker>The product / Understand</Kicker><h2 style={{...title,fontSize:86,marginTop:20}}>See the team. <span style={{color:C.lime}}>Understand the individual.</span></h2></div>
 <div style={{position:'absolute',left:100,top:305,width:928,transform:'scale(.59)',transformOrigin:'top left'}}><ClubDashboard team={f>24} highlight={f>45}/></div>
 <Reveal f={f} at={30} style={{position:'absolute',left:705,top:520}}><Arrow/></Reveal>
 <Reveal f={f} at={44} style={{position:'absolute',left:845,top:305,right:100,height:555,border:`1px solid ${C.line}`,background:C.panel,borderRadius:18,padding:36,boxSizing:'border-box'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:`1px solid ${C.line}`,paddingBottom:24}}><div><div style={{fontSize:36,fontWeight:600}}>Alex Rivera</div><div style={{fontSize:24,color:C.muted,marginTop:8}}>U13 · Midfielder</div></div><Label>ILLUSTRATIVE EXAMPLE</Label></div><div style={{display:'flex',alignItems:'baseline',justifyContent:'space-between',marginTop:24}}><Kicker>Player focus / Control</Kicker><div style={{fontFamily:condensed,fontSize:80,color:C.lime}}>58<span style={{fontFamily:mono,fontSize:23,color:C.muted}}> / 100</span></div></div><h3 style={{...title,fontSize:70,marginTop:20}}>Keep the ball close<br/><span style={{color:C.lime}}>through each turn.</span></h3><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:25,borderTop:`1px solid ${C.line}`,paddingTop:20,fontSize:30}}>Next focus: Figure-8 dribble<Arrow style={{fontSize:36}}/></div></Reveal>
 </>;}

function Workout({f}:{f:number}){const done=f>=138;const seconds=258+Math.floor(f/30);return <>
 <div style={{position:'absolute',left:96,top:210,width:830}}><Kicker>The product / Train</Kicker><h2 style={{...title,fontSize:120,marginTop:34}}>A clear focus.<br/>A practical drill.<br/><span style={{color:C.lime}}>A next step.</span></h2><div style={{fontSize:32,color:C.muted,lineHeight:1.5,marginTop:34}}>Guided sessions in the mobile app.<br/>Track the work. Keep moving.</div><Label style={{marginTop:45}}>Illustrative product preview</Label></div>
 <div style={{position:'absolute',left:1084,top:170,width:730,height:707,border:`2px solid #45614f`,borderRadius:28,background:C.panel,overflow:'hidden'}}><div style={{height:88,boxSizing:'border-box',padding:'21px 27px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:32,fontWeight:600}}>Figure-8 dribble</div><Label>DRILL 1 OF 2</Label></div><div style={{height:323,overflow:'hidden'}}><Freeze frame={f}><OffthreadVideo src={staticFile('figure-8.mp4')} muted style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:'50% 35%'}}/></Freeze></div><div style={{padding:25}}><div style={{display:'flex',justifyContent:'space-between'}}><div><Label style={{fontSize:21}}>{done?'ALL 3 SETS DONE':'SET 3 OF 3 · 60 SEC'}</Label><div style={{display:'flex',gap:14,marginTop:19}}>{[0,1,2].map(n=><div key={n} style={{border:`1px solid ${C.lime}`,background:n<2||done?C.lime:'transparent',color:n<2||done?C.bg:C.muted,width:47,height:47,borderRadius:30,display:'grid',placeItems:'center',fontSize:25}}>{n<2||done?'✓':'3'}</div>)}</div></div><div style={{textAlign:'right'}}><Label style={{color:C.lime}}>{done?'DRILL COMPLETE':'WORKING'}</Label><div style={{fontSize:52,fontVariantNumeric:'tabular-nums',fontWeight:600}}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</div><Label>this session</Label></div></div><div style={{marginTop:18,paddingTop:16,borderTop:`1px solid ${C.line}`,fontSize:26,display:'flex',justifyContent:'space-between'}}><span><span style={{color:C.lime}}>Up next</span> · Wall pass rhythm</span><Arrow style={{fontSize:30}}/></div><div style={{marginTop:18,background:C.lime,color:C.bg,borderRadius:8,padding:'12px 18px',textAlign:'center',fontSize:25,fontWeight:600}}>{done?'Next drill →':'Complete set 3 of 3'}</div></div></div>
 </>;}

function Retest({f}:{f:number}){const q=p(f,25,80);return <>
 <div style={{position:'absolute',left:96,top:174,width:820}}><Kicker>The development cycle</Kicker><h2 style={{...title,fontSize:120,marginTop:31}}>Measure.<br/>Act.<br/><span style={{color:C.lime}}>Learn. Repeat.</span></h2><div style={{fontSize:31,color:C.muted,lineHeight:1.5,marginTop:26}}>Each assessment informs<br/>the next training decision.</div></div>
 <div style={{position:'absolute',left:945,top:213,right:100,padding:35,border:`1px solid ${C.line}`,background:C.panel,borderRadius:18}}><Kicker>Same player. Same test.</Kicker><div style={{fontSize:35,margin:'23px 0 10px'}}>Dribbling shuttle</div><Label>Alex Rivera · U13 · Illustrative example</Label>{[{label:'Earlier assessment',value:7.12},{label:'Latest assessment',value:6.94}].map((v,i)=><div key={i} style={{marginTop:28}}><div style={{display:'flex',alignItems:'baseline',justifyContent:'space-between'}}><span style={{fontSize:26,color:C.muted}}>{v.label}</span><span style={{fontFamily:condensed,fontSize:72,color:i?C.lime:C.ink}}>{v.value.toFixed(2)}<span style={{fontFamily:mono,fontSize:22}}> sec</span></span></div><div style={{height:12,background:C.line,marginTop:12}}><div style={{height:'100%',background:i?C.lime:'#819b8b',width:`${v.value/10*100*q}%`}}/></div></div>)}<div style={{display:'flex',justifyContent:'space-between',marginTop:12}}><Label>0</Label><Label>Time · seconds</Label><Label>10</Label></div><Label style={{marginTop:25,fontSize:18}}>Illustrative change · Not a promised outcome</Label></div>
 <div style={{position:'absolute',left:96,right:100,top:780,display:'flex',alignItems:'center',justifyContent:'space-between'}}>{['Test','Plan','Train','Retest','Refine'].map((x,i)=><React.Fragment key={x}><div style={{fontFamily:condensed,fontSize:54,color:i<=Math.floor(f/55)?C.lime:C.muted,textTransform:'uppercase'}}><span style={{fontFamily:mono,fontSize:20,marginRight:18}}>0{i+1}</span>{x}</div>{i<4&&<Arrow style={{fontSize:40,opacity:.6}}/>}</React.Fragment>)}</div>
 </>;}

function Partnership({f}:{f:number}){return <>
 <div style={{position:'absolute',left:96,top:167}}><Kicker>Built alongside clubs</Kicker><h2 style={{...title,fontSize:104,marginTop:29}}>Show up. Listen. <span style={{color:C.lime}}>Build what matters.</span></h2></div>
 <div style={{position:'absolute',left:96,top:357,width:700}}><Label style={{color:C.lime}}>FIRST CLUB PARTNER</Label><h3 style={{...title,fontSize:110,marginTop:24}}>Vacaville<br/>United.</h3><div style={{fontSize:31,color:C.muted,marginTop:26,lineHeight:1.5}}>Real sessions.<br/>Real feedback.<br/>A product shaped at the field.</div><Label style={{marginTop:31,fontSize:18}}>Partnership described in the September 2026 deck</Label></div>
 <div style={{position:'absolute',left:940,top:358,right:110}}>{[['01','Run sessions','Testing and individual training'],['02','Listen closely','Players, coaches and club leaders'],['03','Improve together','Turn feedback into the next iteration']].map(([num,h,b],i)=><Reveal key={num} f={f} at={i*38} style={{padding:'26px 0 29px',borderTop:`1px solid ${C.line}`,display:'flex',gap:28}}><div style={{fontFamily:mono,fontSize:24,color:C.lime,paddingTop:9}}>{num}</div><div><div style={{fontSize:41,fontWeight:600}}>{h}</div><div style={{fontSize:27,color:C.muted,marginTop:12}}>{b}</div></div></Reveal>)}</div>
 </>;}

function Business({f}:{f:number}){return <>
 <div style={{position:'absolute',left:96,top:169}}><Kicker>The business model</Kicker><h2 style={{...title,fontSize:104,marginTop:28}}>One club relationship.<br/><span style={{color:C.lime}}>Connected value for players.</span></h2></div>
 <Reveal f={f} style={{position:'absolute',left:96,top:484,width:755,borderTop:`3px solid ${C.lime}`,paddingTop:29}}><Label style={{color:C.lime}}>CLUB SERVICES</Label><h3 style={{...title,fontSize:77,marginTop:22}}>Testing +<br/>club platform</h3><div style={{fontSize:29,color:C.muted,marginTop:26}}>On-field delivery. Team and player insight.</div></Reveal>
 <Reveal f={f} at={55} style={{position:'absolute',left:898,top:608}}><Arrow/></Reveal>
 <Reveal f={f} at={64} style={{position:'absolute',left:1055,top:484,right:100,borderTop:`3px solid ${C.line}`,paddingTop:29}}><Label style={{color:C.lime}}>PLANNED / PLAYER SUBSCRIPTION</Label><h3 style={{...title,fontSize:77,marginTop:22}}>Individual<br/>development</h3><div style={{fontSize:29,color:C.muted,marginTop:26}}>Extend support between club sessions.</div></Reveal>
 </>;}

function Expansion({f}:{f:number}){const x=(lon:number)=>(lon+125)/59*1080,y=(lat:number)=>(50-lat)/26*500;const bay=[x(-122.2),y(37.8)],east=[x(-76),y(40.5)];return <>
 <div style={{position:'absolute',left:96,top:172}}><Kicker>Expansion strategy</Kicker><h2 style={{...title,fontSize:105,marginTop:27}}>Grow through<br/><span style={{color:C.lime}}>relationships.</span></h2><div style={{fontSize:30,color:C.muted,lineHeight:1.5,marginTop:31,width:570}}>Start nearby. Build the playbook.<br/>Expand region by region.</div><Label style={{marginTop:39,color:C.lime}}>YOUTH SOCCER FIRST</Label></div>
 <div style={{position:'absolute',left:708,top:258}}><svg width="1110" height="590" viewBox="-15 -35 1120 610"><path d={map.coordinates.flatMap(poly=>poly.map(r=>r.map(([lon,lat],i)=>`${i?'L':'M'}${x(lon).toFixed(2)},${y(lat).toFixed(2)}`).join(' ')+'Z')).join(' ')} fill="#102d21" stroke="#3d5c49" strokeWidth="2"/><path d={`M${bay[0]},${bay[1]} Q460,-65 ${east[0]},${east[1]}`} stroke={C.lime} fill="none" strokeWidth="3" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p(f,50,152)}/><circle cx={bay[0]} cy={bay[1]} r="10" fill={C.lime}/><circle cx={bay[0]} cy={bay[1]} r={20+p(f,0,90)*15} fill="none" stroke={C.lime} opacity=".35"/><g opacity={p(f,142,167)}><circle cx={east[0]} cy={east[1]} r="10" fill={C.lime}/><text x={east[0]-105} y={east[1]+52} fill={C.ink} fontFamily="Inter" fontSize="27">NJ / PA</text></g><text x={bay[0]+20} y={bay[1]+52} fill={C.ink} fontFamily="Inter" fontSize="27">Bay Area</text></svg></div>
 <Reveal f={f} at={170} style={{position:'absolute',left:830,top:820,fontSize:30,color:C.muted}}>Bay Area <span style={{color:C.lime}}>→</span> New Jersey / Pennsylvania <span style={{color:C.lime}}>→</span> Broader markets</Reveal>
 </>;}

function Investment({f}:{f:number}){return <>
 <div style={{position:'absolute',left:96,top:169}}><Kicker>What investment enables</Kicker><h2 style={{...title,fontSize:107,marginTop:30}}>Bring the development cycle<br/><span style={{color:C.lime}}>to more players.</span></h2></div>
 <div style={{position:'absolute',left:96,right:96,top:500,display:'flex',gap:70}}>{[['01','Strengthen\nthe product','Testing → insight → training'],['02','Support\nclub delivery','People and tools at the field'],['03','Repeat\nthe playbook','Onboard the next club well']].map(([n,h,b],i)=><Reveal key={n} f={f} at={i*37} style={{flex:1,borderTop:`2px solid ${i===1?C.lime:C.line}`,paddingTop:25}}><Label style={{color:C.lime}}>{n}</Label><h3 style={{...title,fontSize:76,whiteSpace:'pre-line',marginTop:21}}>{h}</h3><div style={{fontSize:27,color:C.muted,marginTop:23}}>{b}</div></Reveal>)}</div>
 </>;}

function Closing({f}:{f:number}){return <>
 <div style={{position:'absolute',left:96,top:185}}><Brand large/><h2 style={{...title,fontSize:126,marginTop:55}}>Start with evidence.<br/><span style={{color:C.lime}}>Train what’s next.</span></h2><div style={{display:'flex',alignItems:'center',gap:40,marginTop:47}}><div style={{fontSize:34,fontWeight:600}}>posetek.net</div><Arrow style={{fontSize:42}}/><div style={{fontSize:30,color:C.muted}}>Discuss the opportunity</div></div></div>
 <div style={{position:'absolute',left:1180,top:150,opacity:.85}}><PoseVisual frame={f} width={690} height={686} compact/></div>
 <Label style={{position:'absolute',left:99,top:840,fontSize:23}}>Elite-level insight, accessible to more players.</Label>
 </>;}

export const InvestorFilm:React.FC<Props>=({audioEnabled=false,captions=[]})=>{const frame=useCurrentFrame();const cap=captions.find(c=>frame/30>=c.start&&frame/30<c.end);const chapters=['THE OPPORTUNITY','OUR MISSION','THE PRODUCT','THE CYCLE','THE FIRST PARTNER','THE MODEL','THE STRATEGY','THE OPPORTUNITY','POSETEK'];const starts=[0,240,510,990,1290,1620,1920,2250,2520];const idx=starts.reduce((a,b,i)=>frame>=b?i:a,0);return <AbsoluteFill style={{background:C.bg,color:C.ink,fontFamily:'Inter,sans-serif',overflow:'hidden'}}><Fonts/>
 <Scene from={0} duration={240}>{f=><Opportunity f={f}/>}</Scene><Scene from={240} duration={270}>{f=><Mission f={f}/>}</Scene>
 <Scene from={510} duration={150}>{f=><Assess f={f}/>}</Scene><Scene from={660} duration={150}>{f=><Profile f={f}/>}</Scene><Scene from={810} duration={180}>{f=><Workout f={f}/>}</Scene>
 <Scene from={990} duration={300}>{f=><Retest f={f}/>}</Scene><Scene from={1290} duration={330}>{f=><Partnership f={f}/>}</Scene><Scene from={1620} duration={300}>{f=><Business f={f}/>}</Scene><Scene from={1920} duration={330}>{f=><Expansion f={f}/>}</Scene><Scene from={2250} duration={270}>{f=><Investment f={f}/>}</Scene><Scene from={2520} duration={180}>{f=><Closing f={f}/>}</Scene>
 <div style={{position:'absolute',left:96,right:96,top:52,display:'flex',alignItems:'center',justifyContent:'space-between',opacity:1-p(frame,2508,2527)}}><Brand/><Label style={{letterSpacing:2}}>PLAYER DEVELOPMENT, CONNECTED.</Label></div>
 {cap&&<div style={{position:'absolute',left:190,right:190,top:932,minHeight:66,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',fontSize:30,lineHeight:1.35,padding:'9px 30px',boxSizing:'border-box',background:'#04130ef5',borderRadius:10}}>{cap.text}</div>}
 <div style={{position:'absolute',left:96,right:96,bottom:35,height:2,background:C.line}}><div style={{height:2,width:`${frame/2699*100}%`,background:C.lime}}/></div><div style={{position:'absolute',left:96,right:96,bottom:52,display:'flex',justifyContent:'space-between'}}><Label style={{fontSize:17,letterSpacing:2}}>{chapters[idx]}</Label><Label style={{fontSize:17,letterSpacing:2}}>POSETEK / INVESTOR INTRODUCTION</Label></div>
 {audioEnabled&&<Audio src={staticFile('audio-investor-v1/master.wav')}/>}
 </AbsoluteFill>;};
