// Port of legacy 404.html (Firebase Hosting default not-found page). The SPA
// router renders this for any URL without a route.
import { useEffect } from "react";
import { injectClarity } from "./clarity";
import "./not-found.scss";

export default function NotFoundPage() {
  useEffect(() => {
    document.title = "Page Not Found";
    injectClarity();
    window.scrollTo(0, 0); // full-page-load parity

  }, []);

  return (
    <div className="pt-notfound">
      <div id="message">
        <h2>404</h2>
        <h1>Page Not Found</h1>
        <p>The specified file was not found on this website. Please check the URL for mistakes and try again.</p>
        <h3>Why am I seeing this?</h3>
        <p>This page was generated by the Firebase Command-Line Interface. To modify it, edit the <code>404.html</code> file in your project's configured <code>public</code> directory.</p>
      </div>
    </div>
  );
}
