import { useId, useState } from "react";
import { DrillMedia } from "../home/product/DrillMedia";
import { drillMedia } from "../home/product/drill-media";
import type { SamplePlayer } from "./coach-samples";

const steps = ["Plan", "Train", "Retest"] as const;
export function DevelopmentJourney({ player, teamName }: { player: SamplePlayer; teamName: string }) {
  const [step, setStep] = useState<(typeof steps)[number]>("Plan");
  const panelId = useId();
  const difference = player.priorDribbleSeconds - player.latestDribbleSeconds;
  const description = step === "Plan" ? "A focus that belongs to the player." : step === "Train" ? "The next session goes with them." : "Compare the evidence. Choose what comes next.";
  return <div className="coach-development">
    <div className="coach-development-top"><div><span className="coach-mini-logo">P</span><strong>{player.name}</strong><span>{teamName}</span></div><span className="coach-micro">Illustrative example</span></div>
    <div className="coach-development-tabs" role="group" aria-label="Explore player development">{steps.map((value,index)=><button type="button" key={value} aria-pressed={step===value} aria-controls={panelId} onClick={()=>setStep(value)}><span>0{index+1}</span>{value}<span aria-hidden="true">↗</span></button>)}</div>
    <div className="coach-development-body" id={panelId}>
      <div className="coach-development-copy"><p className="eyebrow">{step === "Plan" ? "Evidence → Individual focus" : step === "Train" ? "Plan → Player’s phone" : "Retest → Next training focus"}</p><h3>{description}</h3><p>{step === "Plan" ? "PoseTek connects assessment results to focused training, with each player’s needs in view." : step === "Train" ? "Players can see the drill, follow their session, and record their training. Coaches can review their progress." : "Repeat the same test and review what changed. Use that evidence to guide the next training focus."}</p><div className="coach-responsibility"><span>{step === "Plan" ? "POSETEK SUPPORTS" : step === "Train" ? "PLAYERS TRAIN · COACHES REVIEW" : "TOGETHER, REVIEW THE NEXT STEP"}</span><strong>{step === "Plan" ? "The plan and its individual focus" : step === "Train" ? "A shared view of development" : "Results in context, over time"}</strong></div></div>
      <div className={`coach-development-scene is-${step.toLowerCase()}`}>
        {step === "Plan" && <div className="coach-plan-sheet"><div className="coach-plan-heading"><span className="coach-micro">PLAYER DEVELOPMENT PLAN</span><span aria-hidden="true">↗</span></div><span className="coach-plan-player">{player.name}</span><h4>{player.focus}</h4><p>{player.cue}</p><div className="coach-plan-session"><span className="coach-plan-number">01</span><div><strong>{drillMedia[player.drillId].name}</strong><span>Guided setup · Demonstration video</span></div><span aria-hidden="true">→</span></div><div className="coach-plan-progress"><span>Sample program progress</span><strong>{player.completedSessions}<small> / {player.plannedSessions} sessions</small></strong><div role="img" aria-label={`${player.completedSessions} of ${player.plannedSessions} sample sessions logged`}><i style={{width:`${player.completedSessions/player.plannedSessions*100}%`}}/></div></div><span className="coach-plan-note">Different players. Individual priorities.</span></div>}
        {step === "Train" && <div className="coach-training-phone" role="group" aria-label={`${player.name} sample mobile workout`}><div className="app-device"><div className="app-device-screen"><div className="app-device-status" aria-hidden="true"><span>9:41</span><span className="app-device-island"/><span>▰</span></div><div className="app-device-header"><span className="app-device-logo">P</span><span>PoseTek</span><span>Workout</span></div><div className="app-device-content"><div className="app-device-context"><span>{player.name}</span><span>Sample session</span></div><h3>{drillMedia[player.drillId].name}</h3><div className="app-device-media"><DrillMedia drillId={player.drillId} compact/><span>{player.cue}</span></div><div className="coach-phone-next"><span>YOUR NEXT STEP</span><strong>Watch. Set up. Train.</strong></div><span className="app-device-note">Interactive preview · No workout is recorded</span></div><div className="app-device-home"/></div></div></div>}
        {step === "Retest" && <div className="coach-retest-sheet"><div className="coach-plan-heading"><span className="coach-micro">SAME PLAYER. SAME TEST.</span><span aria-hidden="true">↗</span></div><h4>Dribbling shuttle</h4><p>Compare the same setup across assessments.</p><div className="coach-retest-bars">{[{label:"Earlier assessment",value:player.priorDribbleSeconds},{label:"Latest assessment",value:player.latestDribbleSeconds}].map((item,index)=><div key={item.label} data-latest={index===1}><span>{item.label}</span><strong>{item.value.toFixed(2)} <small>sec</small></strong><div className="coach-result-track"><i style={{width:`${item.value/10*100}%`}}/></div></div>)}<div className="coach-result-axis"><span>0</span><span>Time · seconds</span><span>10</span></div></div><div className="coach-retest-change"><strong>{Math.abs(difference).toFixed(2)}<small> sec {difference >= 0 ? "faster" : "slower"}</small></strong><span>Illustrative change · Not a promised outcome</span></div><p className="coach-plan-note">Measure the change. Revisit the focus.</p></div>}
      </div>
    </div>
  </div>;
}
