// Original PoseTek authoring. Each row has a real coaching distinction; no copied exercise prose.
// Columns: name|equipment|load families|objective IDs|setup|three steps|cue|error to correct|
// regression|progression|comparison IDs|distinctness|per side|loaded|difficulty|dose code
export const exercises = [];
function add(category, week, text) {
  for (const line of text.trim().split('\n')) {
    const cells = line.trim().split('|').map(x => x.trim());
    for(const i of [0,4,5,6,7,8,9,11]) cells[i]=cells[i]?.replace(/([a-z])(\d)/g,'$1 $2').replace(/(\d)(m\b|degrees\b|degree\b)/g,'$1 $2');
    if (cells.length !== 16) throw new Error(`Expected16 columns: ${cells[0]} (${cells.length})`);
    const [name,equipment,families,objectives,setup,steps,cue,error,easier,harder,compared,distinctness,perSide,loaded,level,doseCode] = cells;
    exercises.push({category,week,name,equipment:equipment==='-'?[]:equipment.split(','),families:families.split(','),objectives:objectives==='-'?[]:objectives.split(','),setup,steps:steps.split(';'),cue,error,easier,harder,comparedWith:compared==='-'?[]:compared.split(','),distinctness,perSide:perSide==='1',loaded:loaded==='1',level:Number(level),doseCode});
  }
}

add('strength',1,`
Goblet squat|kettlebell|knee,hip,trunk|vertical_jump|Stand on a clear level floor holding the coach-selected kettlebell at the chest. Practise the unloaded pattern first.|Set feet in a comfortable stance and brace gently;Sit between the hips while keeping the whole foot grounded;Stand smoothly and finish tall without leaning back|Keep the bell close and knees following the toes.|Heels lifting: reduce depth and practise without the bell.|Unloaded squat to a comfortable depth.|Coach increases the load only after consistent depth and control.|STR-001|Adds external anterior loading and an unsupported squat after the existing box competency drill; not another box-height variant.|0|1|2|R
Elevated kettlebell deadlift|kettlebell,box|hip,hamstring,trunk|horizontal_jump|Place a coach-selected kettlebell on a stable low block between the feet. Set a height that permits a comfortable hinge.|Push the hips back and grip the handle;Stand by driving the feet into the floor with arms long;Return the bell to the block under control and reset|Move the hips back before the knees bend deeply.|Rounding to reach: raise the start height or reduce load.|Unloaded hip hinge with hands on the hips.|Coach lowers the start height before increasing weight.|STR-003|Bilateral externally loaded floor-pull preparation differs from the existing single-leg balance reach.|0|1|2|R
Dumbbell floor press|dumbbells,mat|upperPush,trunk|-|Lie on a mat with knees bent and the coach-selected dumbbells held above the chest. Coach helps position weights if needed.|Set shoulders comfortably and hold wrists over elbows;Lower until the upper arms gently meet the floor;Press upward without banging the weights together|Keep wrists stacked and breathe through the press.|Flaring elbows: bring them to a comfortable diagonal and reduce load.|Practise the press pattern with very light dumbbells.|Coach progresses load while the floor remains the depth limit.|-|Introduces horizontal upper-body pressing absent from the existing strength roster.|0|1|2|R
Chest-supported dumbbell row|dumbbells,bench|upperPull|-|Set a stable incline bench so the chest is supported and feet reach the floor. Use coach-selected dumbbells.|Let the arms hang while keeping the neck comfortable;Row elbows toward the hips without lifting the chest;Lower slowly until the arms lengthen|Keep chest contact with the pad.|Shrugging and arching: lighten the weights and shorten the pull.|Use a lighter load with the same chest support.|Coach adds load after smooth full-range repetitions.|-|Adds supported horizontal pulling without requiring the unsupported hinge balance of a bent-over row.|0|1|2|R
Dumbbell reverse lunge|dumbbells|knee,hip,trunk|planned_change_direction|Stand in a clear lane holding coach-selected dumbbells at the sides. Mark a comfortable backward step.|Step one foot back and lower in control;Keep the front foot planted while the back knee approaches the floor;Push through the front foot to return and reset before repeating|Land the back foot quietly and keep the pelvis level.|Stepping on a tightrope: widen the stance slightly.|Unloaded reverse lunge with a nearby support.|Coach adds load after both sides remain steady.|STR-002|Dynamic backward stepping under load adds an eccentric/concentric demand beyond the existing static split squat.|1|1|3|R
Seated dumbbell calf raise|dumbbells,bench|calf|-|Sit on a stable bench with knees bent and feet flat. Rest coach-selected dumbbells on padded thighs and hold them securely.|Press through the forefeet to lift the heels;Pause briefly without rolling the ankles outward;Lower the heels slowly to the floor|Keep the knees still while the ankles move.|Bouncing the weight: pause at each end and lighten it.|Seated heel raises without external load.|Coach increases load after full controlled repetitions.|STR-004|Bent-knee seated loading is a distinct calf-strength emphasis from the standing calf progression; source-specific transfer is unproven.|0|1|2|R
Standing cable anti-rotation press|cableMachine|trunk|-|Set the cable at chest height. Stand side-on with a coach-selected light load and enough room to extend the hands.|Hold the handle close to the chest and brace;Press straight forward while keeping shoulders and hips facing ahead;Return slowly without turning toward the cable|Let the arms move while the trunk stays quiet.|Rotating with the handle: reduce load and widen the stance.|Stand closer to the cable with a lighter load.|Coach narrows the stance or adjusts load, one change at a time.|STR-005|Dynamic anti-rotation pressing expands trunk coverage beyond lateral support holds.|1|1|2|R
`);
add('strength',2,`
Dumbbell Romanian deadlift|dumbbells|hip,hamstring,trunk|horizontal_jump|Stand with coach-selected dumbbells at the thighs. Choose a hinge depth that maintains control rather than reaching the floor.|Soften the knees and send the hips backward;Lower the weights close to the legs while the back stays steady;Drive the hips forward to stand without leaning back|Stop the descent when the hips can no longer move back comfortably.|Turning it into a deep squat: keep a small stable knee bend.|Practise the hinge without weights.|Coach adds load after the descent and return are controlled.|STR-003|Bilateral loaded lengthening hinge differs from the existing unweighted single-leg reach and elevated deadlift starting on a block.|0|1|3|R
Low-box dumbbell step-up|dumbbells,box|knee,hip,trunk|vertical_jump|Use a stable low box that allows the full leading foot to fit. Hold coach-selected weights and leave clear space around it.|Place one foot fully on the box;Rise through the leading leg while keeping the pelvis level;Step down slowly and reset on the same side|Use the upper leg rather than bouncing off the floor.|Pushing hard with the trailing foot: reduce box height or load.|Unloaded step-up onto a lower platform.|Coach increases load before considering a higher box.|-|Adds single-leg stepping through a raised support; distinct from a ground-level lunge.|1|1|3|R
Standing single-arm cable row|cableMachine|upperPull,trunk|-|Stand facing a chest-height cable in a stable split stance. Select a light coach-approved load.|Reach the working arm forward without rounding;Pull the handle toward the ribs with the torso facing ahead;Return slowly and keep the stance still|Keep the belt buckle facing the machine.|Twisting to finish the row: reduce load and shorten the pull.|Use both hands on the handle with a stable stance.|Coach permits a small load increase after control on both sides.|-|Adds unilateral pulling with anti-rotation, unlike the bilateral chest-supported row.|1|1|2|R
Half-kneeling dumbbell overhead press|dumbbells,kneePad|upperPush,trunk|-|Kneel on one knee with the other foot forward. Hold one light coach-selected dumbbell at shoulder height on the kneeling side.|Set the ribs above the pelvis;Press upward through a comfortable shoulder range;Lower smoothly without leaning backward|Finish tall rather than arching the lower back.|Side leaning: use less weight and widen the kneeling base.|Seated light dumbbell press with back support.|Coach adjusts load after a steady press on each side.|-|Introduces vertical pressing with reduced leg assistance and a visible trunk-control requirement.|1|1|3|R
Supine slider hamstring curl|sliders,mat|hamstring,hip|-|Lie on a mat with heels on sliders on a smooth clear floor. Bend the knees and lift the hips to a comfortable bridge.|Brace and slide the heels away a short distance;Keep the pelvis level as far as control allows;Pull the heels back and lower the hips to reset|Use a range you can return from smoothly.|Hips dropping during the slide: shorten the distance.|Slide one heel at a time with the hips resting on the mat.|Coach lengthens the slide before adding repetitions.|STR-006,STR-007|Continuous sliding knee flexion differs from bridge walkout steps and assisted Nordic lowering.|0|0|3|R
Standing cable hip adduction|cableMachine|adductor,hip|-|Use a secure low-cable ankle cuff fitted by the coach. Stand beside the machine with a hand on a fixed support.|Start with the working leg slightly away from the body;Bring it toward the midline without swinging the pelvis;Return slowly without pulling across the standing foot|Keep the toes and pelvis facing forward.|Trunk swinging: lighten the load and reduce the range.|Side-lying unweighted hip adduction taught by the coach.|Coach increases load only with a steady pelvis.|STR-008|Dynamic adjustable hip adduction complements the existing short-lever isometric support; no injury-prevention promise.|1|1|3|R
Single-arm suitcase carry|dumbbells,markers|trunk,hip|-|Mark a clear 10-m lane with turning space. Pick up one coach-selected dumbbell using the taught lifting pattern.|Stand tall with the weight at one side;Walk slowly without leaning or letting the weight swing;Set the weight down under control before changing sides|Keep both shoulders level.|Leaning away from the weight: reduce load or shorten the lane.|Static unloaded marching with level shoulders.|Coach extends the lane before increasing load.|-|Adds anti-lateral-flexion while walking under asymmetrical load rather than a stationary plank.|1|1|2|C
`);
add('strength',3,`
High-handle trap-bar deadlift|trapBar,weightPlates|hip,knee,trunk|vertical_jump,horizontal_jump|Coach checks the trap bar, handles and plate security. Stand centered using an approved starting height and load.|Hinge and bend the knees to grip both handles;Brace and stand while keeping the bar level;Lower onto the floor with control and reset every repetition|Push the floor away and keep the handles level.|Jerking off the floor: lower the load and rebuild the setup.|Elevated kettlebell deadlift with coach instruction.|Coach progresses load only after repeated clean resets.|-|Introduces a centered bilateral bar lift with different grip/setup from kettlebell or dumbbell hinges.|0|1|4|R
Front-foot-elevated dumbbell split squat|dumbbells,box|knee,hip,trunk|planned_change_direction|Place the front foot on a secure shallow platform. Hold coach-selected weights and set a comfortable split stance.|Lower vertically while keeping the front foot planted;Use only the range that keeps the pelvis controlled;Rise through the front leg without springing off the rear foot|Let the front knee travel naturally while the heel stays down.|Excessive depth and tipping: reduce platform height and range.|Ground-level unloaded split squat.|Coach increases range before increasing load.|STR-002|A controlled range-expansion progression from the existing split-squat hold, with dynamic external loading.|1|1|3|R
Cable lat pulldown|cableMachine,bench|upperPull|-|Coach fits the seat and thigh restraint on a lat-pulldown station. Use a light approved load and a comfortable grip.|Sit tall with feet supported;Pull the handle toward the upper chest without leaning far back;Return until the arms comfortably lengthen|Lead with the elbows, not a backward body swing.|Pulling behind the neck: keep the handle in front and reduce load.|Lighter pulldown with a shorter comfortable range.|Coach adds load while preserving the same torso position.|-|Adds scalable vertical pulling rather than another horizontal row.|0|1|2|R
Incline dumbbell bench press|dumbbells,bench|upperPush|-|Set a stable shallow incline bench. Coach helps select and position dumbbells; keep the feet supported.|Hold the weights above the upper chest;Lower in control through a comfortable shoulder range;Press upward without arching off the bench|Keep the feet planted and shoulders supported.|Dropping too deep: limit the range and lighten the load.|Dumbbell floor press.|Coach adds load after consistent shoulder comfort and control.|-|Changes pressing angle and available range from floor pressing; a planned progression, not a renamed flat press.|0|1|3|R
Bench-supported dumbbell hip thrust|dumbbells,bench,mat|hip,hamstring,trunk|-|Secure a bench against movement. Support the upper back on it and place a padded coach-selected dumbbell across the hips.|Set the feet so the shins are comfortable at the top;Lift the hips while keeping the ribs down;Lower slowly without letting the weight roll|Finish by extending the hips, not arching the back.|Overextending at the top: lower the load and stop earlier.|Unloaded floor bridge.|Coach adds load while the bench and weight remain secure.|STR-006|External hip-extension loading from supported shoulders differs from hamstring walkout steps.|0|1|3|R
Cable pull-through|cableMachine|hip,hamstring,trunk|horizontal_jump|Attach a rope to a low cable. Face away and take a stable stance with a coach-approved light load.|Hold the rope between the legs and hinge backward;Stand by bringing the hips forward without pulling with the arms;Return slowly while keeping the cable clear of the legs|Keep the arms long and let the hips do the work.|Being pulled backward: lower the resistance and reset the stance.|Unloaded hinge or elevated kettlebell deadlift.|Coach increases load after balance and hinge control are consistent.|-|Cable resistance pulls backward through the hinge and teaches a different force direction from gravity-loaded dumbbells.|0|1|3|R
Half-kneeling cable chop|cableMachine,kneePad|trunk,upperPull|-|Set a cable above shoulder height. Kneel side-on in a stable half-kneeling stance with a light coach-selected load.|Hold the handle with both hands near the high side;Guide it diagonally across the body while the pelvis stays steady;Return slowly without being pulled off balance|Turn through a comfortable upper-body range without yanking.|Twisting the knee or arching: reduce the range and load.|Standing anti-rotation press.|Coach expands the diagonal range before increasing load.|-|Adds controlled diagonal trunk/arm coordination beyond straight anti-rotation pressing; not a shot-speed treatment.|1|1|3|R
`);
add('strength',4,`
Machine leg press|legPressMachine|knee,hip|vertical_jump|Coach confirms the machine fits, adjusts the seat and explains the stops. Use an approved light load and foot position.|Release the stops as instructed and lower in control;Stop before the pelvis rolls or the heels lift;Press smoothly without forcefully locking the knees|Maintain contact with the back pad throughout.|Descending too far: shorten the range and reset the seat.|Goblet squat or unloaded squat if the machine does not fit.|Coach increases load after fit and depth stay consistent.|STR-001|Machine-supported adjustable loading offers an alternative when a suitable machine fits; not an automatic upgrade for age.|0|1|3|R
Dumbbell lateral lunge|dumbbells|adductor,knee,hip|planned_change_direction|Stand in a clear space holding light coach-selected dumbbells. Mark a comfortable side step.|Step sideways and sit into the stepping hip;Keep the other leg long while both feet stay grounded;Push back to the start and regain balance|Keep the knee following the toes of the stepping foot.|Rolling onto the inner foot: reduce step width and load.|Unloaded shallow side lunge.|Coach increases comfortable range before load.|-|Introduces frontal-plane loaded strength distinct from reverse or split-stance lunges.|1|1|3|R
Seated leg-curl machine|legCurlMachine|hamstring|-|Coach adjusts the seat, thigh pad and ankle pad to fit. Choose a light approved load and comfortable knee range.|Keep the pelvis against the seat;Bend the knees smoothly to draw the pad down and back;Return slowly without letting the weight stack slam|Move at the knees while the hips remain still.|Arching or lifting off the seat: check fit and reduce load.|Short-range slider curl under coach instruction.|Coach expands the pain-free range before increasing resistance.|STR-006,STR-007|Machine-scaled knee flexion provides external loading distinct from bodyweight bridge or Nordic progressions.|0|1|2|R
Band-assisted pull-up|pullUpBar,resistanceBand,box|upperPull,trunk|-|Coach secures and checks the assistance band, bar and step. Mount under supervision; do not jump into the band.|Start with a comfortable active hang;Pull the chest toward the bar without kicking;Lower smoothly and use the step to dismount safely|Use a smooth pull and keep the legs quiet.|Swinging or snapping the band: stop and increase assistance.|Cable lat pulldown.|Coach reduces assistance only after controlled full repetitions.|-|Closed-chain vertical pulling with assistance differs from seated cable pulling and requires a safe mounting procedure.|0|1|4|R
Single-arm dumbbell overhead carry|dumbbells,markers|upperPush,trunk|-|Coach confirms a comfortable overhead hold with a light dumbbell. Mark a short clear lane; no low fixtures nearby.|Press or receive the weight overhead as taught;Walk slowly with ribs over the pelvis and elbow steady;Stop, lower the weight safely and change sides|Keep the arm stable without forcing an end range.|Leaning back: reduce the weight and shorten the carry.|Half-kneeling light overhead press.|Coach lengthens the lane before changing load.|-|Overhead load stability while walking is a distinct progression from the low suitcase carry.|1|1|4|C
Incline-bench dumbbell Y raise|dumbbells,bench|upperPull|-|Lie chest-down on a shallow incline bench with very light coach-selected weights. Leave room for the arms to move forward.|Set the neck comfortably and let arms hang;Lift the arms into a wide Y through a comfortable range;Lower slowly while the chest remains supported|Reach long rather than shrugging the shoulders.|Lifting too high with a shrug: reduce range and use less weight.|Unweighted supported Y raise.|Coach adds only a small load after consistent control.|-|Adds shoulder-elevation/scapular control rather than duplicating rows or pulldowns; general development only.|0|1|3|R
Split-stance single-arm cable press|cableMachine|upperPush,trunk|-|Set one cable at chest height behind the athlete. Adopt a stable split stance with a coach-approved light load.|Hold the handle beside the chest and brace;Press forward without rotating the pelvis;Return slowly and maintain the same stance|Keep both hips facing forward.|Turning the whole body to finish: lower resistance.|Dumbbell floor press or two-hand light cable press.|Coach increases resistance after both sides stay stable.|-|Unilateral standing pressing adds anti-rotation and stance control beyond supported bilateral pressing.|1|1|3|R
`);

add('isometric',1,`
Wall-supported squat hold|wall|knee,hip|-|Use a clear solid wall and non-slip floor. Slide to a shallow coach-approved squat depth with feet far enough forward for balance.|Set the back against the wall and feet flat;Hold the position while breathing normally;Slide upward to stand before form changes|Choose a hold depth you can maintain without strain.|Sliding lower to chase fatigue: return to the approved shallow depth.|Higher wall-supported position for a shorter hold.|Coach lengthens the hold before changing depth.|STR-002|Bilateral supported knee/hip hold differs from the existing unilateral split-squat hold.|0|0|1|H
Supported calf-raise hold|wall|calf|-|Stand near a wall for light balance support. Rise only to a height the coach has taught and approved.|Lift both heels smoothly;Keep equal pressure through both forefeet while holding;Lower with control before the ankles wobble|Hold height rather than bouncing.|Rolling outward onto the small toes: lower slightly and rebalance.|Lower heel-rise height with the same wall support.|Coach introduces a single-leg hold only after review.|STR-004|Sustained ankle force at a fixed position differs from dynamic calf-raise repetitions; no tendon-treatment claim.|0|0|2|H
Quadruped bear-hover hold|mat|trunk,upperPush|-|Start on hands and knees on a mat with hands under shoulders and knees under hips.|Brace gently and lift the knees just clear of the mat;Keep the back level and breathe without shifting backward;Lower the knees softly before control fades|Keep the hover low.|Hips rising high: lower the knees and reset.|Keep both knees on the mat while practising the brace.|Coach adds a few seconds while the low position stays unchanged.|STR-005,STR-501,STR-502|Stationary four-point hover is a prerequisite for the live travelling bear crawl and alternating shoulder taps; it keeps all supports fixed and prescribes hold seconds.|0|0|2|H
`);
add('isometric',2,`
Heel-dig long-lever bridge hold|mat|hamstring,hip,trunk|-|Lie on a mat with heels farther from the hips than a standard bridge. Use the distance selected by the coach.|Press the heels down and gently lift the pelvis;Hold level hips while breathing normally;Lower and relax before the next effort|Keep pressure through both heels.|Cramping or losing height: stop and shorten the lever.|Standard bent-knee floor bridge hold.|Coach moves the heels slightly farther away before longer holds.|STR-006|Static long-lever heel loading differs from travelling bridge walkout steps.|0|0|3|H
Tall-kneeling cable anti-rotation hold|cableMachine,kneePad|trunk|-|Kneel tall side-on to a chest-height cable. Use a light coach-approved load and extend the hands comfortably.|Stack the ribs over the pelvis;Hold the hands still in front without turning;Bring the handle back to the chest before relaxing|Keep pressure even through both knees.|Leaning away from the cable: reduce load.|Hold the handle nearer the chest.|Coach increases arm reach before adding load.|STR-005|Static anti-rotation in tall kneeling removes the standing base used in the dynamic press.|1|1|2|H
Prone small-range trunk hold|mat|trunk|-|Lie face-down with arms beside the body and forehead near the mat. Coach selects a very small comfortable lift.|Lengthen through the crown of the head;Lift the chest only slightly without throwing the head back;Hold briefly while breathing then lower slowly|Think long rather than high.|Large lower-back arch: reduce the lift or keep the chest down.|Prone brace without lifting the chest.|Coach extends hold time only within the same small range.|-|Adds posterior trunk endurance; it is general preparation, not treatment for back pain.|0|0|2|H
`);
add('isometric',3,`
Incline push-up midpoint hold|bench|upperPush,trunk|-|Place hands on a stable fixed bench. Step back into an incline plank; coach selects a manageable elbow bend.|Lower a small distance with the body in one line;Hold without locking the breath or dropping the hips;Press back up and step forward to finish|Keep the whole body aligned.|Sagging hips: use a higher support and shorter hold.|Straight-arm incline support hold.|Coach lowers the support only after steady midpoint holds.|-|Static elbow-bent upper-body support is distinct from the bear hover and floor press.|0|0|3|H
Supported single-leg hinge hold|wall|hip,hamstring,trunk|-|Stand beside a wall for light support. Hinge on one leg into the range selected by the coach.|Move the free leg back as the torso tips forward;Hold the pelvis level without twisting;Return to standing slowly before switching sides|Keep the standing knee softly bent.|Opening the hip outward: reduce the hinge range.|Two-foot hinge hold with hands supported.|Coach reduces hand support before extending hold time.|STR-003|Fixed-position unilateral hinge endurance differs from the existing dynamic single-leg reach.|1|0|3|H
Seated ball-squeeze hold|ball,bench|adductor|-|Sit on a stable bench with feet flat and a soft ball between the knees. Use gentle-to-moderate effort directed by the coach.|Sit tall and settle the ball between the knees;Squeeze steadily while continuing to breathe;Release gradually before the next hold|Use smooth pressure, not a maximal squeeze.|Holding the breath: reduce effort and shorten the hold.|Very gentle shorter squeezes.|Coach increases hold time while effort remains controlled.|STR-008|Bilateral supported adductor squeeze differs from the existing side-supported Copenhagen hold and cable adduction.|0|0|1|H
`);
add('isometric',4,`
Half-kneeling dumbbell overhead hold|dumbbells,kneePad|upperPush,trunk|-|Adopt a stable half-kneeling stance and use a light coach-selected dumbbell. Confirm the overhead position is comfortable.|Bring the weight overhead using the taught press;Hold with ribs down and normal breathing;Lower under control before switching sides|Keep the hand above the shoulder without leaning.|Arching backward: reduce load or use a lower hand position.|Half-kneeling unloaded overhead reach hold.|Coach extends hold time before increasing weight.|-|Stationary overhead stability precedes overhead carrying and is distinct from dynamic pressing.|1|1|3|H
Seated cable-row hold|cableMachine,bench|upperPull,trunk|-|Sit facing a low cable with feet supported and a coach-approved light load. Hold the handle near the lower ribs.|Sit tall and set the shoulder blades comfortably;Hold the elbows beside the body without shrugging;Let the arms extend slowly to finish|Keep the chest still while breathing.|Leaning backward to hold the weight: reduce resistance.|Shorter hold with a lighter load.|Coach extends the hold before changing resistance.|-|Static upper-pull endurance differs from the dynamic row variations.|0|1|2|H
Seated hip-flexion self-resisted hold|bench|hip,trunk|-|Sit upright on a bench with feet supported. Place both hands on the thigh just above one knee; coach sets a moderate effort.|Lift the knee slightly toward the hands;Press the hands gently downward while keeping the thigh still;Release gradually and place the foot down|Keep the pelvis level and breathe normally.|Leaning back to lift the knee: lower the effort.|Unresisted brief seated knee lift.|Coach extends hold time without increasing to maximal effort.|-|Adds low-equipment hip-flexor force practice absent from hip-extension and adductor entries; general support only.|1|0|2|H
`);

add('plyometric',1,`
Two-foot jump-rope rebounds|jumpRope|calf,knee|vertical_jump|Use a correctly sized rope on a level non-slip surface with clear overhead space. Begin with small two-foot jumps.|Turn the rope with the wrists;Clear it with a low quiet rebound using both feet;Stop and reset the rope when rhythm or landing control is lost|Stay low and let the rope set the rhythm.|Large tiring jumps: slow the rope and reduce jump height.|Step over a stationary rope before linking rebounds.|Coach increases consecutive contacts before tempo.|VJP-004|Adds rope timing and constrained repeat contacts to the existing free pogo series; a coordination progression, not extra jump height.|0|0|2|Q
Lateral two-foot line hops|markers|calf,knee,hip|planned_change_direction|Mark a low visual line on a clear level surface. Stand with both feet beside it and choose a narrow hop width.|Rebound sideways across the line with both feet together;Land softly and return across the line;Stop after the planned contacts before rhythm deteriorates|Keep the hops narrow and the knees soft.|Drifting forward or widening: reduce width and reset.|Side-step across the line without hopping.|Coach increases contacts before changing width.|VJP-004,HJP-005|Repeated small bilateral lateral rebounds differ from vertical pogos and large alternating lateral bounds.|0|0|2|Q
Low-box jump with step-down|box|knee,hip,calf|vertical_jump|Coach sets a stable low box that can be reached without excessive knee tucking. Clear the landing surface and provide a safe step-down route.|Dip briefly and jump onto the box with both feet;Stand balanced after a quiet full-foot landing;Step down one foot at a time and reset on the floor|Land tall enough to control the box, not in a deep tuck.|Box too high: lower it rather than pulling knees sharply upward.|Unloaded ground jump and stick already in the library.|Coach improves consistency at the same low height before progression.|VJP-001,VJP-008|Landing onto a low raised surface with a step-down differs from ground landing and excludes dropping from the box.|0|0|3|J
Wall plyometric push-off|wall|upperPush,trunk|-|Stand facing a solid wall with hands at chest height. Coach selects a shallow body angle and checks the wall surface.|Bend the elbows to approach the wall as one line;Push away quickly so the hands briefly leave the wall;Meet the wall softly with bent elbows and reset|Use a small controlled push-off.|Stiff-arm return: reduce the angle and catch softly.|Slow wall push-up without leaving the wall.|Coach increases the body angle before considering a lower support.|-|Introduces upper-body stretch-shortening practice; no direct six-test performance claim.|0|0|2|J
`);
add('plyometric',2,`
Alternating-foot jump-rope rhythm|jumpRope|calf,knee,hip|short_sprint|Use a fitted rope and clear non-slip area. First demonstrate two-foot rope control.|Turn the rope at an easy rhythm;Alternate the landing foot while keeping each rebound low;Stop and reset if a foot catches or posture changes|Count every landing as one contact.|Bouncing too high on one leg: slow down and reduce height.|Two-foot jump-rope rebounds.|Coach extends the alternating sequence before increasing tempo.|VJP-004|Alternating support changes the unilateral rhythm demand from two-foot rope rebounds; supportive, not proven sprint transfer.|0|0|3|Q
Single-leg forward-back line hops|markers|calf,knee,hip|horizontal_jump|Mark a flat line with clear space ahead and behind. Coach confirms repeated single-leg landing competence.|Hop a small distance forward across the line;Rebound backward across it on the same foot;Stop in balance after the planned contacts then change legs|Keep the movements small and predictable.|Large backward jumps or knee collapse: reduce the range and stop.|Two-foot forward-back line steps or hops.|Coach adds contacts only after equal control both directions.|HJP-004|Repeated fore-aft reactive hopping differs from a forward hop with a held landing.|1|0|3|Q
Hopscotch single-to-double landings|markers|knee,hip,calf|planned_change_direction|Lay out a short alternating pattern of one central mark and two side marks. Keep each spacing small.|Hop from one foot to a two-foot landing;Push from two feet into the next single-foot landing;Finish in balance and walk back before changing the starting foot|Match the landing shape to the marks.|Rushing past the marks: shorten the spacing.|Step through the same single-to-double pattern.|Coach lengthens the pattern before increasing spacing.|VJP-006,HJP-004|Practises transitions between one- and two-foot support rather than repeated same-leg or bilateral jumps.|0|0|3|Q
Medicine-ball rebound chest pass|medicineBall,wall|upperPush,trunk|-|Coach selects a light rebound-safe medicine ball and a suitable clear wall. Stand far enough away to receive a gentle rebound.|Push the ball from the chest toward the wall;Receive the rebound with bent elbows and a steady trunk;Redirect it smoothly then stop before catching quality declines|Let the arms absorb the ball before the next push.|Rigid catching or uncontrolled rebound: use a lighter ball and lower speed.|Separate each gentle chest pass with a full catch and reset.|Coach links a few rebounds before increasing speed.|-|Upper-body reactive catch-and-pass develops a distinct power skill; not evidence that it raises soccer shot speed.|0|1|3|J
`);
add('plyometric',3,`
Medicine-ball rotational rebound pass|medicineBall,wall|trunk,hip,upperPush|-|Stand side-on to a suitable clear wall with a light rebound-safe medicine ball. Coach checks the turning space and starts with gentle throws.|Turn the hips and trunk together to pass the ball sideways to the wall;Receive the gentle rebound with soft arms while allowing the body to turn;Redirect smoothly then stop and reset before changing sides|Let the feet turn with the hips rather than twisting a planted knee.|Throwing too hard to receive safely: reduce speed and catch fully.|Gentle side pass followed by a complete catch and reset.|Coach links a few low-force returns after consistent receiving.|-|Transverse-plane reactive trunk and arm work differs from the straight chest rebound; replaces a proposed skip that overlapped the live A Series Circuit.|1|1|3|J
Quarter-turn jump and stick|markers|knee,hip,calf,trunk|planned_change_direction|Place a starting mark and a second facing direction at a quarter turn. Use a clear level surface.|Dip and make a small two-foot jump;Turn the whole body a quarter turn in the air;Land softly facing the new direction and hold before resetting|Turn the trunk and feet together.|Twisting after the feet land: reduce the turn and jump size.|Step-and-turn into the same landing stance.|Coach improves both turn directions before adding repetitions.|VJP-001|Adds controlled transverse-plane orientation to the existing straight jump-and-stick drill.|1|0|3|J
Split-stance switch jump|markers|knee,hip,calf|vertical_jump|Take a short split stance on a clear surface. Coach first confirms a controlled split squat and small jump.|Dip a little through both knees;Jump only high enough to swap the front and back feet;Land softly in the opposite split stance and reset|Keep the stance short and the landing quiet.|Deep uncontrolled lunge landing: shorten the stance and reduce height.|Step-switch the feet without a jump.|Coach links two switches only after stable isolated landings.|STR-002,VJP-006|Bilateral split-stance takeoff and leg switching differ from single-leg vertical jumps and static split holds.|0|0|4|J
Two-step approach vertical jump|markers|knee,hip,calf|vertical_jump|Mark a short two-step approach ending at a takeoff zone. No overhead ball or target is required.|Walk or jog two controlled steps into a two-foot plant;Use the arms and legs to jump upward;Land on two feet and regain balance before walking back|Make the last steps controlled rather than long.|Running too fast into the plant: slow the approach.|Standing countermovement jump already in the library.|Coach increases approach rhythm only when landing remains stable.|VJP-003|Converts a short approach into upward impulse rather than duplicating stationary countermovement jumps.|0|0|3|J
`);
add('plyometric',4,`
Lateral power skips|markers|hip,knee,calf|planned_change_direction|Mark a short sideways lane with no obstacles. Coach demonstrates a low controlled side-skip rhythm.|Push sideways and lift the leading knee slightly;Land and bring the trailing foot through without crossing;Continue for the planned contacts then reverse after rest|Travel sideways without turning into a forward run.|Crossing the feet: slow down and shorten the side travel.|Side-step with a small rise.|Coach extends the lane while keeping the same low rhythm.|HJP-005|Skipping includes an intervening step and rhythm change, unlike continuous alternating lateral bounds.|1|0|3|Q
Backward two-foot hop and stick|markers|knee,hip,calf|planned_change_direction|Check the landing space behind the athlete and mark a very short backward distance. Coach supervises the first attempts.|Look at the clear landing zone before starting;Make a small two-foot hop backward;Land quietly and hold balance before walking forward to reset|Keep the hop short enough to control.|Leaning far backward: shorten the hop.|Backward step and balanced stop.|Coach increases distance only slightly after consistent control.|VJP-001,HJP-002|Adds backward landing orientation, unlike existing forward-distance and vertical landings.|0|0|3|J
Incline plyometric push-up|bench|upperPush,trunk|-|Use a fixed non-slip bench or high platform selected by the coach. Confirm normal incline push-ups and wall push-offs first.|Lower with the body in one line;Push quickly until the hands briefly leave the support;Land the hands softly with bent elbows and reset|Keep the push-off small and the support steady.|Stiff arms or sagging hips: use a higher support.|Wall plyometric push-off.|Coach lowers the support only after repeated controlled catches.|-|A greater relative-load progression from wall push-offs; separate film shows support setup and landing demands.|0|0|4|J
Alternating forward bounds|markers|hip,knee,hamstring,calf|horizontal_jump,short_sprint|Mark a short clear lane. Coach selects modest distances and confirms stable single-leg landings.|Push forward from one leg and land on the opposite leg;Continue with alternating arms and legs for the planned contacts;Finish balanced and walk back for full recovery|Land under control rather than reaching for distance.|Heel reaching and loud landing: reduce bound distance.|Walking exaggerated strides with a pause.|Coach adds a small amount of distance before more contacts.|HJP-003,HJP-004|Alternating contralateral bounds differ from same-leg hop repeats and bilateral triple broad jumps.|0|0|4|Q
`);

add('speedCod',1,`
Two-point split-stance acceleration|cones|hip,knee,hamstring,calf|short_sprint|Mark a 10-m running lane and generous slowing zone. Set a stationary split stance with no falling or floor start.|Lean slightly from the ankles with one foot forward;Push into the first steps and accelerate smoothly through the finish;Slow down gradually beyond the finish and walk back|Push the ground behind you during the first steps.|Popping upright immediately: use a shorter relaxed effort.|March into a gentle 5-m acceleration.|Coach increases speed after repeatable starting posture.|SPD-002,SPD-004|A stable upright split start is a teachable alternative to falling and push-up starts, with no balance-loss or floor transition.|1|0|2|S
Lateral shuffle braking|cones|adductor,knee,hip|planned_change_direction|Mark a 3-m sideways lane with an extra clear stopping zone. Begin at a moderate shuffle pace.|Shuffle sideways without crossing the feet;Use shorter final steps to reduce speed;Finish balanced at the end mark and walk back|Lower gradually before the stop.|Crossing the feet at the stop: reduce entry speed.|Side-walk and stop in balance.|Coach slightly increases entry speed while the stop remains controlled.|COD-002|Braking from a lateral shuffle differs from the existing forward-running deceleration gate.|1|0|2|S
Wide-arc curved acceleration|cones|hip,knee,hamstring,calf|short_sprint|Set cones along a gentle 15-m arc with a clear exit. Choose a wide radius and dry consistent surface.|Build speed gradually along the arc;Lean slightly with the whole body rather than bending at the waist;Run through the exit and slow down in open space|Let the curve guide the lean.|Cutting sharply between cones: widen the arc and slow down.|Jog the same wide arc.|Coach increases speed before reducing the radius.|SPD-006,SPD-009|Continuous curved running differs from straight build-and-fly work and a single planted cut; direct sprint-test transfer is uncertain.|1|0|3|S
`);
add('speedCod',2,`
Side-on crossover acceleration|cones|hip,knee,hamstring,calf|short_sprint|Stand side-on to a clear 8-m lane with a generous slowing area. Coach selects the first crossover step.|Turn the hips toward the lane using a smooth crossover;Continue into forward running for the remaining distance;Slow down gradually and reset to practise the opposite side|Turn into the lane before building speed.|Tangling the feet: rehearse the first two steps slowly.|Walking crossover into a jog.|Coach increases speed after clean direction changes from both sides.|SPD-002,COD-011|Starts sideways with a crossover rather than pressing forward, reacting and recovering; a discrete orientation-to-acceleration skill.|1|0|3|S
Planned 135-degree cut|cones|knee,hip,adductor|planned_change_direction|Mark a short approach and an exit turning back at about135degrees. Begin with a controlled jogging approach.|Shorten the final approach steps to brake;Plant and redirect toward the angled return lane;Accelerate a few steps out then slow down fully|Brake before the turn, not only on the final foot.|Overrunning the corner: lower entry speed.|Walk the same obtuse-angle turn.|Coach increases approach speed only after stable turns both ways.|COD-003,COD-004,COD-005|An intermediate obtuse cut bridges existing45/90degree and180degree tasks; requires its own braking and exit coaching.|1|0|3|S
Shuffle-to-crossover transition|cones|adductor,hip,knee|planned_change_direction|Mark 3m of lateral shuffle followed by a 5-m lateral travel lane. Keep the route clear and preplanned.|Shuffle to the first marker facing forward;Change smoothly to crossover running without a full stop;Finish in balance and walk back before repeating the other way|Change foot pattern without rushing.|Feet colliding at transition: slow the approach and rehearse.|Walk the shuffle-to-crossover pattern.|Coach increases travel speed while preserving coordination.|COD-001|A specified lateral gait transition differs from the mixed-movement corner game and a single side-on sprint start.|1|0|3|S
`);
add('speedCod',3,`
Half-kneeling acceleration start|cones,kneePad|hip,knee,hamstring,calf|short_sprint|Place a knee pad at the start of an 8-m lane with clear run-off. One knee rests down and the other foot is forward.|Lean slightly forward and brace;Push through the front foot to rise directly into running;Accelerate through the finish then slow down gradually|Rise forward rather than standing straight up first.|Using a deep awkward first step: reduce speed and rehearse the rise.|Half-kneeling rise into a walk.|Coach increases speed after controlled starts from both knees.|SPD-004|Unilateral kneeling-to-running is a distinct floor-transition progression from a bilateral push-up start.|1|0|3|S
Backpedal drop-step acceleration|cones|hip,knee,hamstring,calf|planned_change_direction|Mark a 3-m backward lane and a diagonal 6-m forward exit. Check the rear space before every effort.|Backpedal under control to the turning mark;Open the hip with a drop step toward the exit;Run forward through the exit and slow down safely|Turn the hips before trying to sprint.|Twisting over a planted foot: slow down and rehearse the step.|Backward walk into the same turn.|Coach increases backward speed before exit speed.|COD-011,COD-001|Starts with backward travel and a preplanned open turn, rather than the existing press-to-reactive-recovery sequence.|1|0|3|S
Curve-to-straight acceleration|cones|hip,knee,hamstring,calf|short_sprint|Lay out a gentle 8-m curve joining a straight8-m lane. Leave space beyond the finish to slow down.|Build controlled speed along the curve;Gradually align the body with the straight lane;Continue running without a sharp planted cut and then decelerate|Let the curve unwind smoothly.|Sudden pivot at the join: widen the connection and reduce pace.|Jog from the arc onto the straight lane.|Coach increases speed after smooth transitions both directions.|SPD-009|Practises exiting a curve without a planted cut, progressing the wide-arc task while preserving continuous running.|1|0|3|S
`);
add('speedCod',4,`
Accelerate-float-accelerate run|cones|hip,knee,hamstring,calf|short_sprint|Mark three consecutive8-m zones and a clear slowing area. Coach sets submaximal controlled speeds and explains the float.|Build speed through the first zone;Maintain relaxed forward rhythm through the middle zone;Increase speed smoothly again in the final zone before slowing down|Float means relaxed running, not braking.|Stopping in the middle: reduce the pace and rehearse.|Jog-float-jog with clear zone boundaries.|Coach increases speed without turning it into an exhaustion set.|SPD-006,SPD-010|Within-run pace modulation differs from a single build-and-fly effort and repeated short-rest sprints.|0|0|4|S
Backward-running brake and hold|cones|knee,hip,calf|planned_change_direction|Mark a short clear backward lane and a generous stopping space. Coach checks the surface and rear visibility.|Run backward at a controlled pace;Shorten the steps progressively before the stop mark;Finish balanced and turn to walk back|Keep backward steps short enough to manage.|Leaning far backward: slow down and use smaller steps.|Backward walking stop.|Coach increases speed only with predictable stopping distance.|COD-002|Backward braking adds a different travel orientation from the existing forward deceleration gate.|0|0|3|S
Lateral crossover brake and square|cones|adductor,knee,hip|planned_change_direction|Mark a 5-m sideways lane and an extra stopping zone. Practise crossover running slowly before adding a stop.|Travel sideways with crossover steps;Uncross the feet into shorter steps before the finish;Stop facing forward with a stable wide-enough base|Uncross before the final stop.|Trying to stop with crossed feet: slow down and add an uncross step.|Side-walk, uncross and hold.|Coach increases approach pace before shortening the stopping zone.|COD-002|Braking out of crossover gait differs from forward braking and shuffle braking; a distinct foot-organization progression.|1|0|3|S
`);

add('ball',1,`
Self-drop instep cushion receive|ball,markers|hip,knee|-|Stand inside a small marked control area with a ball. Use a low self-drop and no overhead service.|Drop the ball from around waist height;Meet it with the instep and soften the receiving leg;Let the ball settle within one step then pick it up to reset|Give with the ball rather than kicking it upward.|Ball bouncing away: use a lower drop and softer contact.|Drop and trap after one ground bounce.|Coach varies the drop slightly while keeping the same control area.|PAS-003,BMA-502|Introduces an explicit aerial-to-ground instep cushion rather than receiving a ground pass under pressure.|1|0|2|B
Drop-bounce instep juggling|ball|hip,knee|-|Use one ball in a clear personal space. Begin with a hand drop and allow a ground bounce between touches.|Drop the ball and let it bounce once;Lift it with a gentle instep touch no higher than waist level;Let it bounce again and repeat before catching to reset|Keep touches low and the ankle steady.|Kicking too hard: catch and restart with a smaller touch.|One drop, one touch and a catch.|Coach removes a bounce only after several controlled touches.|BM-001,BM-002|Aerial rebound timing differs from ground toe taps and foundations; progression develops ball familiarity rather than measured dribble speed.|1|0|2|B
Outside-foot ground pass|ball,cones|hip,knee|-|Set a wide target gate3-5m away with a clear return path. Begin with a stationary ball and comfortable stance.|Place the support foot beside the ball;Use the outer instep to send the ball through the gate;Follow the pass naturally and retrieve it before changing feet|Use a small controlled swing.|Forcing the ankle sideways: reduce power and review the contact surface.|Shorter outside-foot pass through a wider gate.|Coach adds a moving ball before increasing distance.|PAS-002,BM-005|Teaches a different passing contact surface rather than another inside-foot passing gate or inside-outside dribble.|1|0|3|P
`);
add('ball',2,`
Thigh-to-foot aerial receive|ball,markers|hip,knee|-|Stand in a clear marked area with one ball. Start with a gentle self-toss just above the thigh.|Lift one thigh to meet the falling ball;Lower it slightly on contact to soften the touch;Let the ball drop to the foot for a controlled ground touch|Meet the ball with the thigh, not the knee point.|Popping the ball high: lower the toss and soften the thigh.|Thigh cushion then catch the ball.|Coach adds a gentle partner toss after consistent self-toss control.|PAS-003|Uses a thigh cushion before foot control, distinct from existing ground first-touch routes.|1|0|2|B
Sole layoff to supporting partner|ball,cones|hip,knee|-|A partner stands2-3m diagonally behind. Check that space, then place a stationary ball under the working foot.|Look toward the supporting partner before moving the ball;Roll the ball backward with the sole into the partner's path;Release the foot cleanly and move to receive the return|Choose the pass path before rolling.|Rolling without checking behind: pause and scan first.|Roll to a stationary gate instead of a partner.|Coach adds a gentle incoming pass before the layoff.|BM-003,BM-006,PAS-008|A deliberate sole pass to support differs from individual sole rolls/pull-push mastery and a generic three-player combination.|1|0|2|P
Short-range toe-poke finish|ball,goal,cones|hip,knee|-|Set a close safe shooting distance and a wide target in a secured goal. Coach demonstrates a short controlled toe contact; no goalkeeper is required.|Set the support foot beside the ball;Use a brief forward toe contact with a firm comfortable ankle;Recover balance and retrieve only after the shooting lane is clear|Use a short backswing and modest force.|Jabbing the ground: reset the ball and reduce speed.|Very gentle toe pass through a nearby gate.|Coach introduces a slowly rolling ball before more distance.|SHT-003,SHT-009|Different short-backswing contact technique from laces striking or a generic first-time finish; no maximum shot-speed claim.|1|0|3|K
`);
add('ball',3,`
Chest-to-foot aerial receive|ball,markers|trunk,hip|-|Use a gentle self-toss in a clear area. Keep the ball below head height and start with a comfortable chest-level service.|Move into line with the falling ball;Let the chest soften the contact without heading the ball;Guide the dropping ball to the foot and settle it nearby|Soften the chest rather than striking the ball away.|Ball contacting the face: lower the toss and stop to reset.|Chest cushion followed by a catch.|Coach adds a gentle partner service after self-toss control.|PAS-003,BMA-502|Chest-to-foot aerial control is a new receiving surface and flight condition, not a pressure-receiving rename.|0|0|3|B
Driven instep ground pass|ball,cones|hip,knee|-|Place a wide target gate8-12m away on a clear level surface. Coach selects a manageable distance, not maximum power.|Take a short controlled approach;Contact near the center of the ball with the laces and a steady ankle;Follow through toward the target while keeping the ball low|Prioritize a clean low pass over force.|Leaning back and lifting the ball: shorten the approach.|Short stationary instep pass.|Coach narrows the target before extending distance.|PAS-009,SHT-003|Develops a low driven passing trajectory, distinct from long lofted target passing and shooting for speed.|1|0|3|P
Inside-foot curling finish|ball,goal,cones|hip,knee|-|Mark a short angled approach to a secured goal and a wide finishing zone. Start at a comfortable distance with no goalkeeper.|Approach at a small angle and place the support foot securely;Brush the inside of the foot around the side of the ball;Finish balanced and check the resulting curve before resetting|Use controlled spin rather than maximum power.|Over-rotating or slipping: reduce approach speed.|Short curling pass toward a wide gate.|Coach narrows the target before adding distance.|SHT-502,SHT-003|Explicit spin/contact instruction differs from a far-post target pattern and straight laces-speed practice.|1|0|3|K
`);
add('ball',4,`
Low half-volley wall return|ball,wall,markers|hip,knee|-|Use a suitable clear wall and mark a low target. Stand close enough for a gentle return and begin with a self-drop.|Drop the ball and allow one ground bounce;Meet it just after the bounce with a controlled instep pass;Receive the rebound safely and reset rather than rushing|Time contact after the bounce while the ball is low.|Swinging at a high ball: catch and restart with a lower drop.|Stationary instep pass against the wall.|Coach links two returns only after reliable timing.|BM-025,BM-026,PAS-001|Adds a bounce-timed aerial contact to existing ground wall-pass rhythm; it is not simply a one-touch wall variant.|1|0|3|P
Checked-space backheel pass|ball,cones|hip,knee|-|Place a wide target gate2m behind and slightly to one side. Check the lane, then stand over a stationary ball.|Look back to identify the target before touching the ball;Use a short backward heel movement to pass through the gate;Turn to inspect the result and retrieve the ball safely|Check first, then keep the movement small.|Blindly kicking behind: stop and scan again.|Slow heel nudge to a very wide nearby target.|Coach adds a gentle moving-ball setup before a partner.|PAS-008|Heel contact and verified rearward passing orientation are distinct from sole layoff and inside-foot combinations.|1|0|3|P
Self-drop inside-foot volley pass|ball,cones|hip,knee|-|Mark a wide target gate3-4m away with an empty lane. Use a low self-drop and a controlled service, not a high volley.|Drop the ball below knee height;Meet it with the inside of the foot before it bounces;Recover balance and retrieve after the pass stops|Show a stable inside-foot surface.|Reaching high or losing balance: lower the drop.|Inside-foot pass after one bounce.|Coach introduces a gentle partner toss only after self-drop control.|PAS-002,SHT-009|Direct low aerial passing contact differs from ground gate passes and first-time shooting.|1|0|3|P
`);
